import type { ShowcaseStackCategory } from "./showcase-stack-types";

export const STACK_CATEGORIES: ShowcaseStackCategory[] = [
  {
    id: "core",
    title: "Languages & Frameworks",
    subtitle: "Python · TypeScript · React · Node",
    accent: "grape",
    items: [
      { name: "TypeScript & JavaScript", detail: "Typed scripting", href: "https://www.typescriptlang.org" },
      { name: "Python & Bash", detail: "Automation & scripting", href: "https://www.python.org" },
      { name: "Java & PHP", detail: "Enterprise & web backend", href: "https://www.java.com" },
      { name: "Next.js", detail: "React Framework · App Router", href: "https://nextjs.org" },
      { name: "React & React Native", detail: "Web & Cross-Platform Mobile", href: "https://react.dev" },
      { name: "Node.js & Express.js", detail: "Fast JavaScript APIs", href: "https://nodejs.org" },
      { name: "FastAPI & JAX-RS", detail: "Python & Java APIs", href: "https://fastapi.tiangolo.com" },
      { name: "Tailwind CSS v4", detail: "Utility-first styling", href: "https://tailwindcss.com" },
    ],
  },
  {
    id: "devops",
    title: "DevOps & Cloud",
    subtitle: "CI/CD · containers · cloud",
    accent: "leaf",
    items: [
      { name: "Docker", detail: "Containerization", href: "https://www.docker.com" },
      { name: "Kubernetes", detail: "Container orchestration", href: "https://kubernetes.io" },
      { name: "GitLab CI/CD", detail: "Build & deploy pipelines", href: "https://docs.gitlab.com/ee/ci/" },
      { name: "GitHub Actions", detail: "Workflow automation", href: "https://github.com/features/actions" },
      { name: "AWS EC2", detail: "Cloud compute nodes", href: "https://aws.amazon.com/ec2/" },
      { name: "Linux & Shell", detail: "Systems administration", href: "https://www.linux.org" },
      { name: "Ansible", detail: "Infrastructure as Code", href: "https://www.ansible.com" },
      { name: "Apache Web Server", detail: "Proxying & serving", href: "https://httpd.apache.org" },
    ],
  },
  {
    id: "motion",
    title: "Motion & Visuals",
    subtitle: "Scroll · animation · style",
    accent: "saffron",
    items: [
      { name: "GSAP", detail: "ScrollTrigger · snap animations", href: "https://gsap.com" },
      { name: "Lenis", detail: "Smooth scrolling library", href: "https://lenis.darkroom.engineering" },
      { name: "Framer Motion", detail: "UI transitions & micro-interactions", href: "https://www.framer.com/motion" },
      { name: "RoughJS", detail: "Hand-drawn sketchy vectors", href: "https://roughjs.com" },
      { name: "Lucide React", detail: "Clean vector iconography", href: "https://lucide.dev" },
    ],
  },
  {
    id: "platform",
    title: "Plumbing & Tools",
    subtitle: "Databases · ORM · tools",
    accent: "grape",
    items: [
      { name: "PostgreSQL & MySQL", detail: "Relational storage systems", href: "https://www.postgresql.org" },
      { name: "MongoDB", detail: "NoSQL document store", href: "https://www.mongodb.com" },
      { name: "Prisma ORM", detail: "Type-safe database client", href: "https://www.prisma.io" },
      { name: "REST APIs & Integrations", detail: "GitLab & Google Sheets APIs", href: "https://restfulapi.net" },
      { name: "Sentry & Grafana", detail: "Error tracking & dashboarding", href: "https://sentry.io" },
      { name: "NextAuth.js & Zustand", detail: "Session auth & state management", href: "https://next-auth.js.org" },
      { name: "Vercel", detail: "Serverless static hosting", href: "https://vercel.com" },
      { name: "WordPress & PHP", detail: "Creative web & CMS portals", href: "https://wordpress.org" },
      { name: "Cursor & VS Code", detail: "Pro developers' IDEs", href: "https://cursor.com" },
    ],
  },
];
